apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: "backend"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "backend"
    spec:
      containers:
      - name: replica-backend-container
        image: nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP